#!/usr/bin/env python3
"""
DARPA validator for TT-101 Canon repo.

Rules:
- No silent failures: exit non-zero on any violation.
- Landing page TOC is deterministic and must be generated by tools/build_index.py.
- Manifest exists and is SHA-256 formatted; release statement references current manifest hash.
"""
from __future__ import annotations
import os
import re
import sys
import hashlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PATHS = [
    ROOT / "index.html",
    ROOT / "canon",
    ROOT / "tools" / "build_index.py",
    ROOT / "manifest" / "hashes.txt",
    ROOT / "release" / "RELEASE_v1.0.txt",
]

def fail(msg: str) -> None:
    print("VALIDATION FAIL:", msg, file=sys.stderr)
    sys.exit(1)

def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def main() -> None:
    # Required structure
    for p in REQUIRED_PATHS:
        if not p.exists():
            fail(f"Missing required path: {p.relative_to(ROOT)}")

    # Landing page markers + single TOC
    html = (ROOT / "index.html").read_text(encoding="utf-8", errors="replace")
    if "<!-- TOC:BEGIN -->" not in html or "<!-- TOC:END -->" not in html:
        fail("index.html missing TOC markers <!-- TOC:BEGIN --> / <!-- TOC:END -->")
    toc_count = html.count('class="bd toc"')
    if toc_count != 1:
        fail(f"index.html TOC container count = {toc_count} (expected 1)")

    # TOC must contain enough links (robust window scan)
    idx = html.find('class="bd toc"')
    window = html[idx: idx + 25000] if idx != -1 else ""
    link_count = window.count('<a href="')
    if link_count < 10:
        fail(f"TOC contains too few links: {link_count} (expected >= 10)")

    # Deterministic TOC must be up-to-date
    try:
        subprocess.run(
            ["python3", str(ROOT / "tools" / "build_index.py"), "--check"],
            cwd=str(ROOT),
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as e:
        fail("index.html TOC is out of date. Run: python3 tools/build_index.py")

    # Manifest format and exclusion rule (no circular hashing)
    manifest = (ROOT / "manifest" / "hashes.txt").read_text(encoding="utf-8", errors="replace")
    if "SHA-256" not in manifest:
        fail("manifest/hashes.txt missing header")
    if "release/RELEASE_" in manifest:
        fail("manifest/hashes.txt must not include release statements (circular hashing)")

    # Release must reference current manifest hash
    mf_hash = sha256_file(ROOT / "manifest" / "hashes.txt")
    release = (ROOT / "release" / "RELEASE_v1.0.txt").read_text(encoding="utf-8", errors="replace")
    m = re.search(r"MANIFEST_SHA256:\s*([0-9a-f]{64})", release)
    if not m:
        fail("release/RELEASE_v1.0.txt missing MANIFEST_SHA256 line")
    if m.group(1) != mf_hash:
        fail("release/RELEASE_v1.0.txt MANIFEST_SHA256 does not match manifest/hashes.txt")

    print("VALIDATION OK")
    sys.exit(0)

if __name__ == "__main__":
    main()

# v1.9: extended gates (optional)
def _run_extended_audit():
    try:
        import subprocess, sys, os
        here = os.path.dirname(__file__)
        p = subprocess.run([sys.executable, os.path.join(here,'audit_repo.py')], capture_output=True, text=True)
        if p.returncode != 0:
            raise SystemExit(p.returncode)
    except FileNotFoundError:
        return

try:
    _run_extended_audit()
except SystemExit as e:
    raise

# v2.5: semantic invariants gate
def _run_semantic_lint():
    import os, sys, subprocess
    here = os.path.dirname(__file__)
    cmd = [sys.executable, os.path.join(here, 'semantic_lint.py')]
    p = subprocess.run(cmd, capture_output=True, text=True)
    print(p.stdout)
    if p.returncode != 0:
        print(p.stderr)
        raise SystemExit(p.returncode)

_run_semantic_lint()


# v2.6: link_lint gate
def _run_link_lint():
    import os, sys, subprocess
    here = os.path.dirname(__file__)
    p = subprocess.run([sys.executable, os.path.join(here,'link_lint.py')], capture_output=True, text=True)
    print(p.stdout)
    if p.returncode != 0:
        print(p.stderr)
        raise SystemExit(p.returncode)
_run_link_lint()

# v2.6: orphan_scan gate
def _run_orphan_scan():
    import os, sys, subprocess
    here = os.path.dirname(__file__)
    p = subprocess.run([sys.executable, os.path.join(here,'orphan_scan.py')], capture_output=True, text=True)
    print(p.stdout)
    if p.returncode != 0:
        print(p.stderr)
        raise SystemExit(p.returncode)
_run_orphan_scan()

# v2.6: style_lint gate
def _run_style_lint():
    import os, sys, subprocess
    here = os.path.dirname(__file__)
    p = subprocess.run([sys.executable, os.path.join(here,'style_lint.py')], capture_output=True, text=True)
    print(p.stdout)
    if p.returncode != 0:
        print(p.stderr)
        raise SystemExit(p.returncode)
_run_style_lint()


# v2.8: handbook generation (ensures pages exist)
def _run_build_handbook_pages():
    import os, sys, subprocess
    here = os.path.dirname(__file__)
    cmd = [sys.executable, os.path.join(here, 'build_handbook_pages.py')]
    p = subprocess.run(cmd, capture_output=True, text=True)
    print(p.stdout)
    if p.returncode != 0:
        print(p.stderr)
        raise SystemExit(p.returncode)
_run_build_handbook_pages()

